title: git-wt
description: Enhanced Git worktree management with interactive features
url: https://ahmedelgabri.github.io
baseurl: /git-wt
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

include:
  - index.md
